-- MySQL Script generated by MySQL Workbench
-- 09/26/17 17:24:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET latin1 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`usuario` (
  `usr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usr_nome` VARCHAR(45) NULL DEFAULT NULL,
  `usr_email` VARCHAR(45) NULL DEFAULT NULL,
  `usr_senha` VARCHAR(45) NULL DEFAULT NULL,
  `usr_dt_entrada` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`usr_id`),
  UNIQUE INDEX `usr_email_UNIQUE` (`usr_email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `blog`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`postagem` (
  `pst_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pst_titulo` VARCHAR(45) NULL DEFAULT NULL,
  `pst_conteudo` LONGTEXT NULL DEFAULT NULL,
  `pst_dt_criado` DATE NULL DEFAULT NULL,
  `pst_dt_postado` DATE NULL DEFAULT NULL,
  `usuario_usr_id` INT(11) NOT NULL,
  PRIMARY KEY (`pst_id`),
  INDEX `fk_postagem_usuario_idx` (`usuario_usr_id` ASC),
  CONSTRAINT `fk_postagem_usuario`
    FOREIGN KEY (`usuario_usr_id`)
    REFERENCES `blog`.`usuario` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
